/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/QQGoblin/device-watcher/pkg/apis/device/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNics implements NicInterface
type FakeNics struct {
	Fake *FakeDeviceV1beta1
}

var nicsResource = schema.GroupVersionResource{Group: "device.lqingcloud.cn", Version: "v1beta1", Resource: "nics"}

var nicsKind = schema.GroupVersionKind{Group: "device.lqingcloud.cn", Version: "v1beta1", Kind: "Nic"}

// Get takes name of the nic, and returns the corresponding nic object, and an error if there is any.
func (c *FakeNics) Get(name string, options v1.GetOptions) (result *v1beta1.Nic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(nicsResource, name), &v1beta1.Nic{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Nic), err
}

// List takes label and field selectors, and returns the list of Nics that match those selectors.
func (c *FakeNics) List(opts v1.ListOptions) (result *v1beta1.NicList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(nicsResource, nicsKind, opts), &v1beta1.NicList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.NicList{ListMeta: obj.(*v1beta1.NicList).ListMeta}
	for _, item := range obj.(*v1beta1.NicList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nics.
func (c *FakeNics) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(nicsResource, opts))
}

// Create takes the representation of a nic and creates it.  Returns the server's representation of the nic, and an error, if there is any.
func (c *FakeNics) Create(nic *v1beta1.Nic) (result *v1beta1.Nic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(nicsResource, nic), &v1beta1.Nic{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Nic), err
}

// Update takes the representation of a nic and updates it. Returns the server's representation of the nic, and an error, if there is any.
func (c *FakeNics) Update(nic *v1beta1.Nic) (result *v1beta1.Nic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(nicsResource, nic), &v1beta1.Nic{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Nic), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNics) UpdateStatus(nic *v1beta1.Nic) (*v1beta1.Nic, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(nicsResource, "status", nic), &v1beta1.Nic{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Nic), err
}

// Delete takes name of the nic and deletes it. Returns an error if one occurs.
func (c *FakeNics) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(nicsResource, name), &v1beta1.Nic{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNics) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(nicsResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.NicList{})
	return err
}

// Patch applies the patch and returns the patched nic.
func (c *FakeNics) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Nic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(nicsResource, name, pt, data, subresources...), &v1beta1.Nic{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Nic), err
}
