/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/QQGoblin/device-watcher/pkg/apis/device/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// NicLister helps list Nics.
type NicLister interface {
	// List lists all Nics in the indexer.
	List(selector labels.Selector) (ret []*v1beta1.Nic, err error)
	// Get retrieves the Nic from the index for a given name.
	Get(name string) (*v1beta1.Nic, error)
	NicListerExpansion
}

// nicLister implements the NicLister interface.
type nicLister struct {
	indexer cache.Indexer
}

// NewNicLister returns a new NicLister.
func NewNicLister(indexer cache.Indexer) NicLister {
	return &nicLister{indexer: indexer}
}

// List lists all Nics in the indexer.
func (s *nicLister) List(selector labels.Selector) (ret []*v1beta1.Nic, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.Nic))
	})
	return ret, err
}

// Get retrieves the Nic from the index for a given name.
func (s *nicLister) Get(name string) (*v1beta1.Nic, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("nic"), name)
	}
	return obj.(*v1beta1.Nic), nil
}
